- name: create ~/bin directory 
  file:
    path: ~/bin
    state: directory

- name: Download Telegram 
  unarchive:
    src: https://telegram.org/dl/desktop/linux
    dest: ~/bin
    remote_src: yes
    creates: ~/bin/Telegram/Telegram
#TODO create telegram shortcut before first run
